# Generated by Django 4.2.2 on 2023-06-12 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('image', models.ImageField(upload_to='static/assets/images/all/')),
                ('description', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=64)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.city')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/assets/images/all/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(upload_to='static/assets/images/all/')),
                ('service', models.BooleanField(blank=True, null=True)),
                ('active_date', models.TimeField()),
                ('inactive_date', models.TimeField()),
                ('inactive_day', models.CharField(blank=True, choices=[('Cumartesi', 'Cumartesi'), ('Salı', 'salı'), ('Pazartesi', 'Pazartesi'), ('Pazar', 'Pazar'), ('Perşembe', 'Perşembe'), ('Çarşamba', 'çarşamba'), ('Cuma', 'Cuma')], max_length=64, null=True)),
                ('mekan_type', models.CharField(blank=True, choices=[('Kafe', 'Kafe'), ('Sokak Yemekleri', 'Sokak Yemekleri'), ('Fast-Casual Restoranlar', 'Fast-Casual Restoranlar'), ('Akşam yemek restorantları', 'Akşam yemek restorantları'), ('Restorant', 'Restorant')], max_length=64, null=True)),
                ('description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.city')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.destination')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.district')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.food')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('waiter', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('park', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comfortable', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('air_condition', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cleaning', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('flavor', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('menu_variety', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.restaurants')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.destination'),
        ),
    ]
